apiVersion: v1
kind: Service
metadata:
 name: node_js_app
spec:
 type: NodePort
 selector:
   app: node_js_app
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 3000
   targetPort: 3000
   nodePort: 32220
