apiVersion: v1
kind: Service
metadata:
 name: node-js-app
spec:
 type: NodePort
 selector:
   app: node-js-app
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 3000
   targetPort: 3000
   nodePort: 32223
